# Run BISC regression tests

name: BISC

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Initialize submodules
      run: ls -a && git submodule update --init --recursive

    - name: Build Assembler
      run: make asm

    - name: Build Virtual Machine
      run: make vm

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Test
      run: dotnet test --no-build --verbosity normal