# Run BISC regression tests

name: BISC

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Initialize submodules
      run: git submodule update --init --recursive

    - name: Build Project
      run: make

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Test
      run: ls -a && dotnet test --no-build --verbosity normal